version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - trenscendance

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "443:443"
      - "80:80"
    networks:
      - trenscendance
    depends_on:
      - frontend


networks:
  trenscendance:

